import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/shared/NavBar";
import Footer from "@/shared/Footer";
import ExerciseProvider from "@/context/ExerciseContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <ExerciseProvider>
        <body className="flex flex-col min-h-screen bg-black text-white">
          <NavBar />
          <div className="bg-black flex-1">
            {children}
            <ToastContainer />
          </div>
          <Footer />
        </body>
      </ExerciseProvider>
    </html>
    // <html
    //   lang="en"
    //   className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    // >
    //   <ExerciseProvider>
    //     <body className="min-h-screen bg-black text-white">
    //       <div className="min-h-screen bg-black">
    //         <NavBar />
    //         {children}
    //         <ToastContainer />
    //       </div>
    //       <Footer />
    //     </body>
    //   </ExerciseProvider>
    // </html>
  );
}
